<a href="https://colab.research.google.com/github/mycode-hub/Machine-Learning/blob/master/vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

In [ ]:
a = [1,2,3,4,5]
print (a )

[1, 2, 3, 4, 5]


In [ ]:
a =np.random.rand(1000000)
b =np.random.rand(1000000)
tic =time.time();
#c= np.dot(a,b)
c=a@b
tac=time.time()
print(c)
print( "vectorized time " +  (str)((tac-tic) *1000) + " in ms ")

250133.9466154487
vectorized time 1.73187255859375 in ms 


In [ ]:
c=0
tic =time.time();             #initialize time

for i in range(1000000) :     #element wise calculation of dot product and summation
  c+=a[i]*b[i]
tac=time.time()               #stop time
print(c)
print( "for loop time " +  (str)((tac-tic) *1000) + " in ms ")

250133.94661545355
for loop time 587.5780582427979 in ms 


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])
print(a*b)
print(a@b)
print(np.dot(a,b))

[[1 2]
 [3 4]]
[[3 3]
 [7 7]]
[[3 3]
 [7 7]]
